server:
  port: 80
spring:
  application:
    name: jungle-gateway
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    ip-address: true
zuul:
  # 忽略所有请求
  # ignoredServices: '*'
  routes:
    jungle-user: /user/**
    jungle-web: /web/**
    static:
      path: /static/**
      url: http://localhost:9002/static/
  sensitive-headers:
  add-host-header: true