spring:
  application:
    name: jungle-user
#  profiles: docker
#  profiles:
#    active: dev
  mail:
    host: smtp.163.com
    from: hyz804762373@163.com
    default-encoding: UTF-8
    username:  hyz804762373@163.com
    password:  hyz951226
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

