spring:
  application:
    name: jungle-user
  profiles:
    active: dev
  datasource:
    username: root
    password: root
  mail:
    host: smtp.163.com
    from: hyz804762373@163.com
    default-encoding: UTF-8
    username:  hyz804762373@163.com
    password:  hyz951226
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
