server:
  port: 9002
spring:
  application:
    name: jungle-web
  freemarker:
    #  设定ftl文件路径
    template-loader-path: classpath:/templates/
    # 设置字符编码
    charset: UTF-8
    # 是否及时刷新，线上设为true
    cache: false
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-spring-macro-helpers: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  mvc:
    static-path-pattern: /static/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/