spring:
  application:
    name: jungle-article
  profiles: docker
  datasource:
    username: root
    password: root
    #zipkin管理端微服务的地址
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      #抓取100%的日志,一般在开发环境，该值设置为1，生产环境视情况而定
      probability: 1.0
server:
  port: 9003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/